import {
  FileText, DollarSign, Briefcase, TrendingUp,
  Code, Palette, Terminal,
} from "lucide-react";

export const CATEGORIES = [
  { id: "content", name: "Content", icon: FileText },
  { id: "sales", name: "Sales & Persuasion", icon: DollarSign },
  { id: "business", name: "Business", icon: Briefcase },
  { id: "strategy", name: "Strategy", icon: TrendingUp },
  { id: "technical", name: "Technical", icon: Code },
  { id: "creative", name: "Creative", icon: Palette },
  { id: "code", name: "Code", icon: Terminal },
];

export const TEMPLATES = [
  // ─── Content (6) ───────────────────────────────────────────────────────────
  {
    id: "blog-post",
    category: "content",
    name: "Blog Post Writer",
    description: "Long-form articles with structure, voice constraints, and SEO awareness",
    projectName: "Blog Content Writer",
    domain: "Content marketing",
    projectDesc: "An AI writing assistant that produces structured blog posts with consistent voice, clear section flow, and reader engagement hooks.",
    goals: "Write blog posts that rank in search, engage readers through the full piece, and maintain brand voice consistently across topics",
  },
  {
    id: "newsletter",
    category: "content",
    name: "Newsletter Editor",
    description: "Weekly or bi-weekly email newsletters with audience-aware tone",
    projectName: "Newsletter Editor",
    domain: "Email marketing",
    projectDesc: "An AI assistant that drafts newsletter editions with a consistent editorial voice, curated insights, and clear calls to action for subscriber engagement.",
    goals: "Produce newsletters that maintain high open rates, drive click-throughs, and build reader trust over time",
  },
  {
    id: "linkedin-post",
    category: "content",
    name: "LinkedIn Post Creator",
    description: "Professional social posts optimized for engagement and reach",
    projectName: "LinkedIn Content Creator",
    domain: "Professional social media",
    projectDesc: "An AI assistant that writes LinkedIn posts with hook-first structure, authentic voice, and engagement-driving formatting.",
    goals: "Create posts that generate meaningful engagement, build professional authority, and grow follower base organically",
  },
  {
    id: "twitter-thread",
    category: "content",
    name: "Twitter/X Thread Writer",
    description: "Multi-tweet threads that break down complex topics clearly",
    projectName: "Thread Writer",
    domain: "Social media content",
    projectDesc: "An AI assistant that structures Twitter/X threads with strong hooks, clear progression, and standalone value in each tweet.",
    goals: "Write threads that get bookmarked, shared, and drive profile visits through clear thinking and sharp writing",
  },
  {
    id: "youtube-script",
    category: "content",
    name: "YouTube Script Writer",
    description: "Video scripts with hooks, retention beats, and natural speech flow",
    projectName: "YouTube Script Writer",
    domain: "Video content",
    projectDesc: "An AI assistant that writes video scripts optimized for viewer retention, with natural spoken cadence, pattern interrupts, and clear story structure.",
    goals: "Produce scripts that keep viewers watching, feel natural when spoken aloud, and drive subscribers through consistent value delivery",
  },
  {
    id: "podcast-notes",
    category: "content",
    name: "Podcast Show Notes",
    description: "Episode summaries, timestamps, and promotional copy from transcripts",
    projectName: "Podcast Show Notes Generator",
    domain: "Audio content",
    projectDesc: "An AI assistant that transforms podcast transcripts into structured show notes with timestamps, key takeaways, guest bios, and shareable quotes.",
    goals: "Create show notes that improve discoverability, give listeners quick reference, and serve as standalone content for non-listeners",
  },

  // ─── Sales & Persuasion (5) ────────────────────────────────────────────────
  {
    id: "landing-page",
    category: "sales",
    name: "Landing Page Copy",
    description: "Conversion-focused page copy with clear value proposition and CTAs",
    projectName: "Landing Page Copywriter",
    domain: "Conversion copywriting",
    projectDesc: "An AI assistant that writes landing page copy following problem-agitation-solution structure, with clear value props, objection handling, and action-driving CTAs.",
    goals: "Write landing page copy that converts visitors into signups or buyers by clearly communicating value and removing purchase hesitation",
  },
  {
    id: "cold-outreach",
    category: "sales",
    name: "Cold Outreach Email",
    description: "Personalized cold emails that get replies without being pushy",
    projectName: "Cold Email Writer",
    domain: "Outbound sales",
    projectDesc: "An AI assistant that crafts personalized cold outreach emails that demonstrate research, lead with value, and prompt natural replies.",
    goals: "Write cold emails that achieve above-average reply rates by being relevant, concise, and genuinely helpful rather than salesy",
  },
  {
    id: "sales-page",
    category: "sales",
    name: "Sales Page Writer",
    description: "Long-form sales copy with testimonials, objection handling, and urgency",
    projectName: "Sales Page Copywriter",
    domain: "Direct response copywriting",
    projectDesc: "An AI assistant that produces long-form sales page copy with story-driven leads, benefit stacking, social proof integration, and urgency elements.",
    goals: "Write sales pages that move readers from problem awareness through desire to purchase action using proven direct response frameworks",
  },
  {
    id: "case-study",
    category: "sales",
    name: "Case Study Builder",
    description: "Customer success stories with measurable results and narrative flow",
    projectName: "Case Study Writer",
    domain: "B2B marketing",
    projectDesc: "An AI assistant that structures customer case studies with situation-challenge-solution-result format, quantified outcomes, and quotable pull-outs.",
    goals: "Produce case studies that build buyer confidence by showcasing real results, relatable challenges, and clear transformation narratives",
  },
  {
    id: "product-launch",
    category: "sales",
    name: "Product Launch Announcement",
    description: "Launch emails and announcements that generate excitement and urgency",
    projectName: "Launch Announcement Writer",
    domain: "Product marketing",
    projectDesc: "An AI assistant that writes product launch announcements with clear what's-new framing, benefit-led feature descriptions, and time-sensitive CTAs.",
    goals: "Create launch announcements that drive immediate action, clearly communicate new value, and generate shareable excitement",
  },

  // ─── Business Communication (5) ────────────────────────────────────────────
  {
    id: "executive-summary",
    category: "business",
    name: "Executive Summary",
    description: "Concise briefs for leadership with key decisions and recommendations",
    projectName: "Executive Summary Writer",
    domain: "Business communication",
    projectDesc: "An AI assistant that distills complex information into executive-level summaries with clear recommendations, key metrics, and decision points.",
    goals: "Produce summaries that respect executive time, surface the right information for decisions, and present options with clear trade-offs",
  },
  {
    id: "client-proposal",
    category: "business",
    name: "Client Proposal",
    description: "Professional proposals with scope, timeline, pricing, and next steps",
    projectName: "Proposal Writer",
    domain: "Professional services",
    projectDesc: "An AI assistant that creates client proposals with clear scope definition, phased timelines, transparent pricing, and compelling why-us positioning.",
    goals: "Write proposals that win work by clearly matching client needs to capabilities, removing ambiguity, and making the next step obvious",
  },
  {
    id: "stakeholder-update",
    category: "business",
    name: "Stakeholder Update",
    description: "Progress reports with wins, blockers, and next steps for decision-makers",
    projectName: "Stakeholder Update Writer",
    domain: "Project communication",
    projectDesc: "An AI assistant that produces stakeholder updates with progress highlights, risk flags, resource needs, and clear asks for the audience.",
    goals: "Create updates that keep stakeholders informed without overwhelming them, surface issues early, and make support requests actionable",
  },
  {
    id: "meeting-recap",
    category: "business",
    name: "Meeting Recap",
    description: "Structured meeting notes with decisions, action items, and owners",
    projectName: "Meeting Recap Writer",
    domain: "Team communication",
    projectDesc: "An AI assistant that transforms meeting notes or transcripts into structured recaps with decisions made, action items assigned, and follow-up deadlines.",
    goals: "Produce meeting recaps that prevent context loss, create accountability through clear ownership, and reduce unnecessary follow-up meetings",
  },
  {
    id: "investor-pitch",
    category: "business",
    name: "Investor Pitch Narrative",
    description: "Compelling fundraising narratives with market context and traction proof",
    projectName: "Investor Pitch Writer",
    domain: "Startup fundraising",
    projectDesc: "An AI assistant that crafts investor pitch narratives with market opportunity framing, traction proof points, team credibility, and clear ask structure.",
    goals: "Write pitch narratives that generate investor interest by clearly connecting market opportunity, team capability, and traction evidence",
  },

  // ─── Strategy & Analysis (4) ───────────────────────────────────────────────
  {
    id: "competitor-analysis",
    category: "strategy",
    name: "Competitor Analysis",
    description: "Structured competitive breakdowns with positioning gaps and opportunities",
    projectName: "Competitive Analyst",
    domain: "Market intelligence",
    projectDesc: "An AI assistant that produces structured competitor analyses covering positioning, pricing, features, strengths, weaknesses, and strategic gaps.",
    goals: "Deliver competitor analyses that reveal actionable differentiation opportunities and inform strategic positioning decisions",
  },
  {
    id: "market-research",
    category: "strategy",
    name: "Market Research Brief",
    description: "Market sizing, trends, and opportunity assessments with data-backed insights",
    projectName: "Market Research Analyst",
    domain: "Market research",
    projectDesc: "An AI assistant that creates market research briefs with sizing estimates, trend identification, customer segment profiles, and opportunity scoring.",
    goals: "Produce research briefs that inform go/no-go decisions with data-backed market sizing, validated demand signals, and clear opportunity framing",
  },
  {
    id: "swot-analysis",
    category: "strategy",
    name: "SWOT Analysis",
    description: "Strengths, weaknesses, opportunities, and threats with action recommendations",
    projectName: "SWOT Analyst",
    domain: "Strategic planning",
    projectDesc: "An AI assistant that conducts SWOT analyses with specific, actionable items in each quadrant and cross-quadrant strategic recommendations.",
    goals: "Create SWOT analyses that go beyond generic observations to surface non-obvious strategic moves and prioritized action items",
  },
  {
    id: "positioning-statement",
    category: "strategy",
    name: "Positioning Statement",
    description: "Clear market positioning with target audience, differentiator, and proof",
    projectName: "Positioning Strategist",
    domain: "Brand strategy",
    projectDesc: "An AI assistant that develops positioning statements using the target-category-differentiator-proof framework with competitive context.",
    goals: "Craft positioning statements that clearly communicate unique value, resonate with target buyers, and withstand competitive scrutiny",
  },

  // ─── Technical (4) ─────────────────────────────────────────────────────────
  {
    id: "api-docs",
    category: "technical",
    name: "API Documentation",
    description: "Endpoint documentation with examples, error codes, and integration guides",
    projectName: "API Documentation Writer",
    domain: "Technical writing",
    projectDesc: "An AI assistant that produces API documentation with endpoint descriptions, request/response examples, error handling guides, and authentication flows.",
    goals: "Write API docs that enable developers to integrate successfully on first attempt with minimal support tickets",
  },
  {
    id: "product-guide",
    category: "technical",
    name: "User-Facing Product Guide",
    description: "Help docs and feature guides written for non-technical end users",
    projectName: "Product Guide Writer",
    domain: "User documentation",
    projectDesc: "An AI assistant that creates user-facing product guides with task-oriented structure, visual callouts, and progressive complexity.",
    goals: "Produce guides that reduce support volume by enabling self-service learning for users of all technical levels",
  },
  {
    id: "technical-explainer",
    category: "technical",
    name: "Technical Concept Explainer",
    description: "Complex technical topics explained for non-technical audiences",
    projectName: "Technical Explainer",
    domain: "Technical communication",
    projectDesc: "An AI assistant that translates complex technical concepts into clear explanations for non-technical stakeholders using analogies and progressive depth.",
    goals: "Explain technical concepts so that business stakeholders can make informed decisions without needing engineering backgrounds",
  },
  {
    id: "changelog",
    category: "technical",
    name: "Changelog / Release Notes",
    description: "User-facing release notes that highlight impact over implementation",
    projectName: "Release Notes Writer",
    domain: "Product communication",
    projectDesc: "An AI assistant that writes user-facing release notes emphasizing user impact, benefit framing, and clear migration steps for breaking changes.",
    goals: "Create release notes that users actually read by leading with value delivered rather than technical implementation details",
  },

  // ─── Creative & Brand (3) ──────────────────────────────────────────────────
  {
    id: "brand-voice",
    category: "creative",
    name: "Brand Voice Guide",
    description: "Codified voice and tone guidelines with do/don't examples",
    projectName: "Brand Voice Architect",
    domain: "Brand identity",
    projectDesc: "An AI assistant that develops comprehensive brand voice guides with personality traits, tone spectrum, vocabulary guidelines, and contextual do/don't examples.",
    goals: "Create voice guides that ensure consistent brand expression across all touchpoints, regardless of who is writing",
  },
  {
    id: "origin-story",
    category: "creative",
    name: "Origin Story",
    description: "Founder or brand origin narratives that build trust and connection",
    projectName: "Origin Story Writer",
    domain: "Brand storytelling",
    projectDesc: "An AI assistant that crafts compelling origin stories with relatable struggle, turning-point moments, and mission-driven resolution.",
    goals: "Write origin stories that build emotional connection with the audience and clearly communicate why this brand exists",
  },
  {
    id: "product-description",
    category: "creative",
    name: "Product Description",
    description: "Benefit-driven product copy that sells without overselling",
    projectName: "Product Copywriter",
    domain: "E-commerce copywriting",
    projectDesc: "An AI assistant that writes product descriptions leading with benefits, using sensory language, and addressing buyer objections inline.",
    goals: "Create product descriptions that increase conversion by making buyers feel the outcome before they purchase",
  },

  // ─── Code (3) ──────────────────────────────────────────────────────────────
  {
    id: "code-review",
    category: "code",
    name: "Code Review Assistant",
    description: "Structured code reviews focused on bugs, performance, and maintainability",
    projectName: "Code Review Assistant",
    domain: "Software engineering",
    projectDesc: "An AI assistant that reviews code for correctness, performance, security, and maintainability with prioritized findings and fix suggestions.",
    goals: "Produce code reviews that catch real bugs, surface non-obvious performance issues, and suggest improvements without bikeshedding",
  },
  {
    id: "readme-generator",
    category: "code",
    name: "README Generator",
    description: "Project READMEs with setup instructions, architecture overview, and examples",
    projectName: "README Writer",
    domain: "Developer documentation",
    projectDesc: "An AI assistant that generates project READMEs with quick-start instructions, architecture overview, API examples, and contribution guidelines.",
    goals: "Create READMEs that enable new developers to understand, run, and contribute to a project within 5 minutes of reading",
  },
  {
    id: "bug-report",
    category: "code",
    name: "Bug Report Writer",
    description: "Structured bug reports with reproduction steps and expected behavior",
    projectName: "Bug Report Assistant",
    domain: "QA and debugging",
    projectDesc: "An AI assistant that structures bug reports with clear reproduction steps, environment details, expected vs actual behavior, and severity assessment.",
    goals: "Write bug reports that enable developers to reproduce and fix issues on first attempt without back-and-forth clarification",
  },
];
