import {
  FileText, DollarSign, Briefcase, TrendingUp,
  Code, Palette, Terminal, GraduationCap, HeartPulse,
} from "lucide-react";

export const CATEGORIES = [
  { id: "content", name: "Content", icon: FileText },
  { id: "sales", name: "Sales & Persuasion", icon: DollarSign },
  { id: "business", name: "Business", icon: Briefcase },
  { id: "strategy", name: "Strategy", icon: TrendingUp },
  { id: "technical", name: "Technical", icon: Code },
  { id: "creative", name: "Creative", icon: Palette },
  { id: "code", name: "Code", icon: Terminal },
  { id: "education", name: "Education", icon: GraduationCap },
  { id: "operations", name: "Operations", icon: HeartPulse },
];

export const TEMPLATES = [
  // ─── Content (6) ───────────────────────────────────────────────────────────
  {
    id: "blog-post",
    category: "content",
    tier: "free",
    name: "Blog Post Writer",
    description: "Long-form articles with structure, voice constraints, and SEO awareness",
    projectName: "Blog Content Writer",
    domain: "Content marketing",
    projectDesc: "An AI writing assistant that produces structured blog posts with consistent voice, clear section flow, and reader engagement hooks.",
    goals: "Write blog posts that rank in search, engage readers through the full piece, and maintain brand voice consistently across topics",
  },
  {
    id: "newsletter",
    category: "content",
    tier: "free",
    name: "Newsletter Editor",
    description: "Weekly or bi-weekly email newsletters with audience-aware tone",
    projectName: "Newsletter Editor",
    domain: "Email marketing",
    projectDesc: "An AI assistant that drafts newsletter editions with a consistent editorial voice, curated insights, and clear calls to action for subscriber engagement.",
    goals: "Produce newsletters that maintain high open rates, drive click-throughs, and build reader trust over time",
  },
  {
    id: "linkedin-post",
    category: "content",
    tier: "free",
    name: "LinkedIn Post Creator",
    description: "Professional social posts optimized for engagement and reach",
    projectName: "LinkedIn Content Creator",
    domain: "Professional social media",
    projectDesc: "An AI assistant that writes LinkedIn posts with hook-first structure, authentic voice, and engagement-driving formatting.",
    goals: "Create posts that generate meaningful engagement, build professional authority, and grow follower base organically",
  },
  {
    id: "twitter-thread",
    category: "content",
    tier: "free",
    name: "Twitter/X Thread Writer",
    description: "Multi-tweet threads that break down complex topics clearly",
    projectName: "Thread Writer",
    domain: "Social media content",
    projectDesc: "An AI assistant that structures Twitter/X threads with strong hooks, clear progression, and standalone value in each tweet.",
    goals: "Write threads that get bookmarked, shared, and drive profile visits through clear thinking and sharp writing",
  },
  {
    id: "youtube-script",
    category: "content",
    tier: "free",
    name: "YouTube Script Writer",
    description: "Video scripts with hooks, retention beats, and natural speech flow",
    projectName: "YouTube Script Writer",
    domain: "Video content",
    projectDesc: "An AI assistant that writes video scripts optimized for viewer retention, with natural spoken cadence, pattern interrupts, and clear story structure.",
    goals: "Produce scripts that keep viewers watching, feel natural when spoken aloud, and drive subscribers through consistent value delivery",
  },
  {
    id: "podcast-notes",
    category: "content",
    tier: "free",
    name: "Podcast Show Notes",
    description: "Episode summaries, timestamps, and promotional copy from transcripts",
    projectName: "Podcast Show Notes Generator",
    domain: "Audio content",
    projectDesc: "An AI assistant that transforms podcast transcripts into structured show notes with timestamps, key takeaways, guest bios, and shareable quotes.",
    goals: "Create show notes that improve discoverability, give listeners quick reference, and serve as standalone content for non-listeners",
  },

  // ─── Sales & Persuasion (5) ────────────────────────────────────────────────
  {
    id: "landing-page",
    category: "sales",
    tier: "free",
    name: "Landing Page Copy",
    description: "Conversion-focused page copy with clear value proposition and CTAs",
    projectName: "Landing Page Copywriter",
    domain: "Conversion copywriting",
    projectDesc: "An AI assistant that writes landing page copy following problem-agitation-solution structure, with clear value props, objection handling, and action-driving CTAs.",
    goals: "Write landing page copy that converts visitors into signups or buyers by clearly communicating value and removing purchase hesitation",
  },
  {
    id: "cold-outreach",
    category: "sales",
    tier: "free",
    name: "Cold Outreach Email",
    description: "Personalized cold emails that get replies without being pushy",
    projectName: "Cold Email Writer",
    domain: "Outbound sales",
    projectDesc: "An AI assistant that crafts personalized cold outreach emails that demonstrate research, lead with value, and prompt natural replies.",
    goals: "Write cold emails that achieve above-average reply rates by being relevant, concise, and genuinely helpful rather than salesy",
  },
  {
    id: "sales-page",
    category: "sales",
    tier: "free",
    name: "Sales Page Writer",
    description: "Long-form sales copy with testimonials, objection handling, and urgency",
    projectName: "Sales Page Copywriter",
    domain: "Direct response copywriting",
    projectDesc: "An AI assistant that produces long-form sales page copy with story-driven leads, benefit stacking, social proof integration, and urgency elements.",
    goals: "Write sales pages that move readers from problem awareness through desire to purchase action using proven direct response frameworks",
  },
  {
    id: "case-study",
    category: "sales",
    tier: "free",
    name: "Case Study Builder",
    description: "Customer success stories with measurable results and narrative flow",
    projectName: "Case Study Writer",
    domain: "B2B marketing",
    projectDesc: "An AI assistant that structures customer case studies with situation-challenge-solution-result format, quantified outcomes, and quotable pull-outs.",
    goals: "Produce case studies that build buyer confidence by showcasing real results, relatable challenges, and clear transformation narratives",
  },
  {
    id: "product-launch",
    category: "sales",
    tier: "free",
    name: "Product Launch Announcement",
    description: "Launch emails and announcements that generate excitement and urgency",
    projectName: "Launch Announcement Writer",
    domain: "Product marketing",
    projectDesc: "An AI assistant that writes product launch announcements with clear what's-new framing, benefit-led feature descriptions, and time-sensitive CTAs.",
    goals: "Create launch announcements that drive immediate action, clearly communicate new value, and generate shareable excitement",
  },

  // ─── Business Communication (5) ────────────────────────────────────────────
  {
    id: "executive-summary",
    category: "business",
    tier: "free",
    name: "Executive Summary",
    description: "Concise briefs for leadership with key decisions and recommendations",
    projectName: "Executive Summary Writer",
    domain: "Business communication",
    projectDesc: "An AI assistant that distills complex information into executive-level summaries with clear recommendations, key metrics, and decision points.",
    goals: "Produce summaries that respect executive time, surface the right information for decisions, and present options with clear trade-offs",
  },
  {
    id: "client-proposal",
    category: "business",
    tier: "free",
    name: "Client Proposal",
    description: "Professional proposals with scope, timeline, pricing, and next steps",
    projectName: "Proposal Writer",
    domain: "Professional services",
    projectDesc: "An AI assistant that creates client proposals with clear scope definition, phased timelines, transparent pricing, and compelling why-us positioning.",
    goals: "Write proposals that win work by clearly matching client needs to capabilities, removing ambiguity, and making the next step obvious",
  },
  {
    id: "stakeholder-update",
    category: "business",
    tier: "free",
    name: "Stakeholder Update",
    description: "Progress reports with wins, blockers, and next steps for decision-makers",
    projectName: "Stakeholder Update Writer",
    domain: "Project communication",
    projectDesc: "An AI assistant that produces stakeholder updates with progress highlights, risk flags, resource needs, and clear asks for the audience.",
    goals: "Create updates that keep stakeholders informed without overwhelming them, surface issues early, and make support requests actionable",
  },
  {
    id: "meeting-recap",
    category: "business",
    tier: "free",
    name: "Meeting Recap",
    description: "Structured meeting notes with decisions, action items, and owners",
    projectName: "Meeting Recap Writer",
    domain: "Team communication",
    projectDesc: "An AI assistant that transforms meeting notes or transcripts into structured recaps with decisions made, action items assigned, and follow-up deadlines.",
    goals: "Produce meeting recaps that prevent context loss, create accountability through clear ownership, and reduce unnecessary follow-up meetings",
  },
  {
    id: "investor-pitch",
    category: "business",
    tier: "free",
    name: "Investor Pitch Narrative",
    description: "Compelling fundraising narratives with market context and traction proof",
    projectName: "Investor Pitch Writer",
    domain: "Startup fundraising",
    projectDesc: "An AI assistant that crafts investor pitch narratives with market opportunity framing, traction proof points, team credibility, and clear ask structure.",
    goals: "Write pitch narratives that generate investor interest by clearly connecting market opportunity, team capability, and traction evidence",
  },

  // ─── Strategy & Analysis (4) ───────────────────────────────────────────────
  {
    id: "competitor-analysis",
    category: "strategy",
    tier: "free",
    name: "Competitor Analysis",
    description: "Structured competitive breakdowns with positioning gaps and opportunities",
    projectName: "Competitive Analyst",
    domain: "Market intelligence",
    projectDesc: "An AI assistant that produces structured competitor analyses covering positioning, pricing, features, strengths, weaknesses, and strategic gaps.",
    goals: "Deliver competitor analyses that reveal actionable differentiation opportunities and inform strategic positioning decisions",
  },
  {
    id: "market-research",
    category: "strategy",
    tier: "free",
    name: "Market Research Brief",
    description: "Market sizing, trends, and opportunity assessments with data-backed insights",
    projectName: "Market Research Analyst",
    domain: "Market research",
    projectDesc: "An AI assistant that creates market research briefs with sizing estimates, trend identification, customer segment profiles, and opportunity scoring.",
    goals: "Produce research briefs that inform go/no-go decisions with data-backed market sizing, validated demand signals, and clear opportunity framing",
  },
  {
    id: "swot-analysis",
    category: "strategy",
    tier: "free",
    name: "SWOT Analysis",
    description: "Strengths, weaknesses, opportunities, and threats with action recommendations",
    projectName: "SWOT Analyst",
    domain: "Strategic planning",
    projectDesc: "An AI assistant that conducts SWOT analyses with specific, actionable items in each quadrant and cross-quadrant strategic recommendations.",
    goals: "Create SWOT analyses that go beyond generic observations to surface non-obvious strategic moves and prioritized action items",
  },
  {
    id: "positioning-statement",
    category: "strategy",
    tier: "free",
    name: "Positioning Statement",
    description: "Clear market positioning with target audience, differentiator, and proof",
    projectName: "Positioning Strategist",
    domain: "Brand strategy",
    projectDesc: "An AI assistant that develops positioning statements using the target-category-differentiator-proof framework with competitive context.",
    goals: "Craft positioning statements that clearly communicate unique value, resonate with target buyers, and withstand competitive scrutiny",
  },

  // ─── Technical (4) ─────────────────────────────────────────────────────────
  {
    id: "api-docs",
    category: "technical",
    tier: "free",
    name: "API Documentation",
    description: "Endpoint documentation with examples, error codes, and integration guides",
    projectName: "API Documentation Writer",
    domain: "Technical writing",
    projectDesc: "An AI assistant that produces API documentation with endpoint descriptions, request/response examples, error handling guides, and authentication flows.",
    goals: "Write API docs that enable developers to integrate successfully on first attempt with minimal support tickets",
  },
  {
    id: "product-guide",
    category: "technical",
    tier: "free",
    name: "User-Facing Product Guide",
    description: "Help docs and feature guides written for non-technical end users",
    projectName: "Product Guide Writer",
    domain: "User documentation",
    projectDesc: "An AI assistant that creates user-facing product guides with task-oriented structure, visual callouts, and progressive complexity.",
    goals: "Produce guides that reduce support volume by enabling self-service learning for users of all technical levels",
  },
  {
    id: "technical-explainer",
    category: "technical",
    tier: "free",
    name: "Technical Concept Explainer",
    description: "Complex technical topics explained for non-technical audiences",
    projectName: "Technical Explainer",
    domain: "Technical communication",
    projectDesc: "An AI assistant that translates complex technical concepts into clear explanations for non-technical stakeholders using analogies and progressive depth.",
    goals: "Explain technical concepts so that business stakeholders can make informed decisions without needing engineering backgrounds",
  },
  {
    id: "changelog",
    category: "technical",
    tier: "free",
    name: "Changelog / Release Notes",
    description: "User-facing release notes that highlight impact over implementation",
    projectName: "Release Notes Writer",
    domain: "Product communication",
    projectDesc: "An AI assistant that writes user-facing release notes emphasizing user impact, benefit framing, and clear migration steps for breaking changes.",
    goals: "Create release notes that users actually read by leading with value delivered rather than technical implementation details",
  },

  // ─── Creative & Brand (3) ──────────────────────────────────────────────────
  {
    id: "brand-voice",
    category: "creative",
    tier: "free",
    name: "Brand Voice Guide",
    description: "Codified voice and tone guidelines with do/don't examples",
    projectName: "Brand Voice Architect",
    domain: "Brand identity",
    projectDesc: "An AI assistant that develops comprehensive brand voice guides with personality traits, tone spectrum, vocabulary guidelines, and contextual do/don't examples.",
    goals: "Create voice guides that ensure consistent brand expression across all touchpoints, regardless of who is writing",
  },
  {
    id: "origin-story",
    category: "creative",
    tier: "free",
    name: "Origin Story",
    description: "Founder or brand origin narratives that build trust and connection",
    projectName: "Origin Story Writer",
    domain: "Brand storytelling",
    projectDesc: "An AI assistant that crafts compelling origin stories with relatable struggle, turning-point moments, and mission-driven resolution.",
    goals: "Write origin stories that build emotional connection with the audience and clearly communicate why this brand exists",
  },
  {
    id: "product-description",
    category: "creative",
    tier: "free",
    name: "Product Description",
    description: "Benefit-driven product copy that sells without overselling",
    projectName: "Product Copywriter",
    domain: "E-commerce copywriting",
    projectDesc: "An AI assistant that writes product descriptions leading with benefits, using sensory language, and addressing buyer objections inline.",
    goals: "Create product descriptions that increase conversion by making buyers feel the outcome before they purchase",
  },

  // ─── Code (3) ──────────────────────────────────────────────────────────────
  {
    id: "code-review",
    category: "code",
    tier: "free",
    name: "Code Review Assistant",
    description: "Structured code reviews focused on bugs, performance, and maintainability",
    projectName: "Code Review Assistant",
    domain: "Software engineering",
    projectDesc: "An AI assistant that reviews code for correctness, performance, security, and maintainability with prioritized findings and fix suggestions.",
    goals: "Produce code reviews that catch real bugs, surface non-obvious performance issues, and suggest improvements without bikeshedding",
  },
  {
    id: "readme-generator",
    category: "code",
    tier: "free",
    name: "README Generator",
    description: "Project READMEs with setup instructions, architecture overview, and examples",
    projectName: "README Writer",
    domain: "Developer documentation",
    projectDesc: "An AI assistant that generates project READMEs with quick-start instructions, architecture overview, API examples, and contribution guidelines.",
    goals: "Create READMEs that enable new developers to understand, run, and contribute to a project within 5 minutes of reading",
  },
  {
    id: "bug-report",
    category: "code",
    tier: "free",
    name: "Bug Report Writer",
    description: "Structured bug reports with reproduction steps and expected behavior",
    projectName: "Bug Report Assistant",
    domain: "QA and debugging",
    projectDesc: "An AI assistant that structures bug reports with clear reproduction steps, environment details, expected vs actual behavior, and severity assessment.",
    goals: "Write bug reports that enable developers to reproduce and fix issues on first attempt without back-and-forth clarification",
  },

  // ─── PREMIUM: Content (4) ─────────────────────────────────────────────────
  {
    id: "ghostwriter",
    category: "content",
    tier: "pro",
    name: "Executive Ghostwriter",
    description: "Thought leadership articles written in a specific executive's voice",
    projectName: "Executive Ghostwriter",
    domain: "Thought leadership",
    projectDesc: "An AI writing assistant that produces thought leadership articles matching a specific executive's voice, perspective, and expertise level. Captures their cadence, avoids their pet peeves, and builds on their known positions.",
    goals: "Write articles that readers believe the executive wrote themselves, building their personal brand and industry authority without generic AI tells",
  },
  {
    id: "email-sequence",
    category: "content",
    tier: "pro",
    name: "Email Nurture Sequence",
    description: "Multi-email drip campaigns that move leads through a funnel",
    projectName: "Email Sequence Architect",
    domain: "Email marketing automation",
    projectDesc: "An AI assistant that designs multi-email nurture sequences with strategic timing, progressive disclosure of value, objection handling at each stage, and clear conversion triggers.",
    goals: "Create email sequences that maintain engagement across 5-7 touches, warm leads without being pushy, and convert at predictable rates through each funnel stage",
  },
  {
    id: "seo-pillar",
    category: "content",
    tier: "pro",
    name: "SEO Pillar Page",
    description: "Comprehensive topic authority pages with internal linking strategy",
    projectName: "SEO Pillar Content Writer",
    domain: "SEO content strategy",
    projectDesc: "An AI assistant that creates comprehensive pillar pages covering a topic cluster exhaustively, with strategic H2/H3 structure, internal linking hooks, and featured snippet optimization.",
    goals: "Build pillar pages that establish topical authority, rank for competitive head terms, and serve as link-worthy reference material in the industry",
  },
  {
    id: "webinar-script",
    category: "content",
    tier: "pro",
    name: "Webinar Script",
    description: "Full webinar scripts with engagement beats, Q&A prep, and pitch sections",
    projectName: "Webinar Script Writer",
    domain: "Live content marketing",
    projectDesc: "An AI assistant that writes complete webinar scripts with attention hooks every 5 minutes, audience interaction prompts, Q&A preparation, and a natural transition to offer or CTA.",
    goals: "Produce webinar scripts that maintain live attendance through the full session, generate qualified leads, and convert attendees into customers or next-step takers",
  },

  // ─── PREMIUM: Sales & Persuasion (4) ──────────────────────────────────────
  {
    id: "objection-handler",
    category: "sales",
    tier: "pro",
    name: "Sales Objection Handler",
    description: "Response frameworks for the 10 most common sales objections",
    projectName: "Objection Response Architect",
    domain: "Sales enablement",
    projectDesc: "An AI assistant that develops structured responses to common sales objections using acknowledge-reframe-evidence-advance methodology, tailored to specific product positioning and buyer personas.",
    goals: "Equip sales reps with confident, non-defensive responses that transform objections into buying signals and advance deals forward",
  },
  {
    id: "proposal-follow-up",
    category: "sales",
    tier: "pro",
    name: "Proposal Follow-Up Sequence",
    description: "Strategic follow-up emails after sending a proposal",
    projectName: "Follow-Up Sequence Writer",
    domain: "B2B sales",
    projectDesc: "An AI assistant that creates a 5-touch follow-up sequence for post-proposal engagement, each adding new value rather than just checking in, with escalation triggers and multi-threading tactics.",
    goals: "Keep deals moving after proposal delivery by adding value at each touchpoint, surfacing hidden objections, and preventing ghosting through strategic urgency",
  },
  {
    id: "testimonial-request",
    category: "sales",
    tier: "pro",
    name: "Testimonial Request System",
    description: "Scripts and emails that get customers to provide powerful testimonials",
    projectName: "Testimonial Collection Writer",
    domain: "Social proof marketing",
    projectDesc: "An AI assistant that crafts testimonial request emails, interview scripts, and guided questionnaires that extract specific, results-driven quotes from happy customers.",
    goals: "Collect testimonials that include specific numbers, before/after comparisons, and emotional language that resonates with prospects in similar situations",
  },
  {
    id: "pricing-page",
    category: "sales",
    tier: "pro",
    name: "Pricing Page Copy",
    description: "Pricing page copy that justifies value and reduces comparison shopping",
    projectName: "Pricing Page Strategist",
    domain: "SaaS pricing",
    projectDesc: "An AI assistant that writes pricing page copy with tier differentiation, value anchoring, feature framing by outcome, and strategic FAQ placement to handle price objections.",
    goals: "Create pricing pages that guide buyers to the right tier, justify premium pricing through value framing, and reduce churn from mismatched expectations",
  },

  // ─── PREMIUM: Business (4) ────────────────────────────────────────────────
  {
    id: "board-memo",
    category: "business",
    tier: "pro",
    name: "Board Memo",
    description: "Board-ready memos with strategic context, financials, and asks",
    projectName: "Board Memo Writer",
    domain: "Corporate governance",
    projectDesc: "An AI assistant that produces board-level memorandums with executive context, financial implications, risk assessment, strategic alignment rationale, and clear decision requests.",
    goals: "Write board memos that respect directors' time, present complex decisions clearly, and get approvals by anticipating questions before they're asked",
  },
  {
    id: "hiring-brief",
    category: "business",
    tier: "pro",
    name: "Hiring Brief & Job Description",
    description: "Role briefs that attract A-players and filter mismatches early",
    projectName: "Hiring Brief Writer",
    domain: "Talent acquisition",
    projectDesc: "An AI assistant that creates hiring briefs and job descriptions with clear success metrics, culture signals, anti-requirements that filter bad fits, and compelling why-join narratives.",
    goals: "Attract candidates who self-select accurately, reduce interview-to-hire ratio, and communicate role expectations so clearly that first-day surprises are eliminated",
  },
  {
    id: "partnership-pitch",
    category: "business",
    tier: "pro",
    name: "Partnership Pitch",
    description: "Co-marketing and business partnership proposals with mutual value framing",
    projectName: "Partnership Pitch Writer",
    domain: "Business development",
    projectDesc: "An AI assistant that crafts partnership proposals leading with the partner's benefit, backed by audience overlap data, co-marketing mechanics, and clear success metrics for both sides.",
    goals: "Write partnership pitches that get responses by making the value exchange obvious, the mechanics simple, and the downside risk negligible for the partner",
  },
  {
    id: "quarterly-review",
    category: "business",
    tier: "pro",
    name: "Quarterly Business Review",
    description: "QBR decks and narratives with KPI analysis and forward-looking plans",
    projectName: "QBR Narrative Writer",
    domain: "Business operations",
    projectDesc: "An AI assistant that produces quarterly business review narratives with KPI trend analysis, initiative scorecards, variance explanations, and next-quarter commitments.",
    goals: "Create QBR narratives that demonstrate accountability, surface issues before they escalate, and build stakeholder confidence through transparent progress reporting",
  },

  // ─── PREMIUM: Strategy (4) ────────────────────────────────────────────────
  {
    id: "go-to-market",
    category: "strategy",
    tier: "pro",
    name: "Go-to-Market Plan",
    description: "GTM strategies with channel selection, messaging, and launch sequencing",
    projectName: "GTM Strategist",
    domain: "Product launch strategy",
    projectDesc: "An AI assistant that develops go-to-market plans with ICP definition, channel prioritization, messaging hierarchy, launch timeline, and success metrics per channel.",
    goals: "Build GTM plans that focus resources on highest-leverage channels, sequence activities for compound momentum, and include kill criteria for underperforming bets",
  },
  {
    id: "pricing-strategy",
    category: "strategy",
    tier: "pro",
    name: "Pricing Strategy Analysis",
    description: "Pricing model evaluation with willingness-to-pay and competitive context",
    projectName: "Pricing Strategist",
    domain: "Revenue strategy",
    projectDesc: "An AI assistant that analyzes pricing strategies with value metric identification, competitive positioning, willingness-to-pay estimation, and tier structure optimization.",
    goals: "Develop pricing strategies that capture fair value, minimize churn from price sensitivity, and create natural upgrade paths that align with customer success milestones",
  },
  {
    id: "okr-framework",
    category: "strategy",
    tier: "pro",
    name: "OKR Framework Builder",
    description: "Objectives and key results with measurable outcomes and alignment checks",
    projectName: "OKR Architect",
    domain: "Goal setting and alignment",
    projectDesc: "An AI assistant that builds OKR frameworks with ambitious but achievable objectives, measurable key results, cross-team alignment mapping, and mid-quarter check-in prompts.",
    goals: "Create OKRs that teams actually use for prioritization, that cascade properly across departments, and that drive focus rather than becoming checkbox exercises",
  },
  {
    id: "retention-playbook",
    category: "strategy",
    tier: "pro",
    name: "Customer Retention Playbook",
    description: "Churn prevention strategies with health scoring and intervention triggers",
    projectName: "Retention Strategist",
    domain: "Customer success",
    projectDesc: "An AI assistant that builds customer retention playbooks with health score frameworks, churn risk indicators, intervention scripts for each risk level, and win-back sequences.",
    goals: "Reduce churn by identifying at-risk customers early, equipping CS teams with proven intervention plays, and creating systematic save processes rather than ad-hoc firefighting",
  },

  // ─── PREMIUM: Technical (3) ───────────────────────────────────────────────
  {
    id: "architecture-decision",
    category: "technical",
    tier: "pro",
    name: "Architecture Decision Record",
    description: "ADRs with context, options considered, trade-offs, and final decision",
    projectName: "ADR Writer",
    domain: "Software architecture",
    projectDesc: "An AI assistant that produces architecture decision records with problem context, constraints, options evaluated with trade-off matrices, and clear rationale for the chosen approach.",
    goals: "Create ADRs that future engineers can understand without asking the original author, preventing re-litigation of settled decisions and preserving institutional knowledge",
  },
  {
    id: "incident-postmortem",
    category: "technical",
    tier: "pro",
    name: "Incident Postmortem",
    description: "Blameless postmortems with timeline, root cause, and prevention actions",
    projectName: "Postmortem Writer",
    domain: "Site reliability engineering",
    projectDesc: "An AI assistant that structures incident postmortems with precise timelines, contributing factor analysis, root cause identification, and prioritized remediation actions with owners and deadlines.",
    goals: "Produce postmortems that drive systemic improvement rather than blame, identify the deepest contributing factors, and result in concrete actions that prevent recurrence",
  },
  {
    id: "migration-plan",
    category: "technical",
    tier: "pro",
    name: "Migration Plan",
    description: "System migration plans with rollback strategies and risk matrices",
    projectName: "Migration Planner",
    domain: "Systems engineering",
    projectDesc: "An AI assistant that creates migration plans with phased rollout schedules, data validation checkpoints, rollback procedures for each phase, and communication templates for stakeholders.",
    goals: "Build migration plans that minimize downtime, provide clear go/no-go criteria at each checkpoint, and give the team confidence to execute without heroics",
  },

  // ─── PREMIUM: Creative (3) ────────────────────────────────────────────────
  {
    id: "brand-manifesto",
    category: "creative",
    tier: "pro",
    name: "Brand Manifesto",
    description: "Rallying-cry brand documents that align teams and inspire audiences",
    projectName: "Brand Manifesto Writer",
    domain: "Brand strategy",
    projectDesc: "An AI assistant that crafts brand manifestos with conviction-driven language, clear enemy/ally framing, values articulation, and a memorable closing declaration.",
    goals: "Write manifestos that employees want to print on the wall, that customers share unprompted, and that make the brand's beliefs impossible to misunderstand",
  },
  {
    id: "naming-exploration",
    category: "creative",
    tier: "pro",
    name: "Product Naming Exploration",
    description: "Name generation with linguistic analysis, domain checks, and shortlisting",
    projectName: "Product Naming Consultant",
    domain: "Brand naming",
    projectDesc: "An AI assistant that generates product name candidates with etymological rationale, phonetic analysis, competitive differentiation scoring, and cultural sensitivity checks.",
    goals: "Produce name shortlists that are memorable, ownable, linguistically sound, and aligned with brand positioning rather than generic category descriptors",
  },
  {
    id: "creative-brief",
    category: "creative",
    tier: "pro",
    name: "Creative Brief",
    description: "Agency-quality briefs that align creative teams on objectives and constraints",
    projectName: "Creative Brief Writer",
    domain: "Marketing creative",
    projectDesc: "An AI assistant that produces creative briefs with clear objectives, audience insights, single-minded proposition, mandatory inclusions, tone guidance, and success metrics.",
    goals: "Write briefs that give creative teams enough direction to be excellent without enough restriction to be formulaic, reducing revision cycles through upfront clarity",
  },

  // ─── PREMIUM: Code (2) ────────────────────────────────────────────────────
  {
    id: "pr-review-agent",
    category: "code",
    tier: "pro",
    name: "PR Review Agent",
    description: "Automated PR review with security, performance, and maintainability checks",
    projectName: "Pull Request Reviewer",
    domain: "Software engineering",
    projectDesc: "An AI assistant that reviews pull requests across security vulnerabilities, performance regressions, test coverage gaps, API contract changes, and maintainability concerns with severity-ranked findings.",
    goals: "Catch issues that human reviewers miss under time pressure, reduce review turnaround time, and maintain consistent quality standards across the entire codebase",
  },
  {
    id: "test-generator",
    category: "code",
    tier: "pro",
    name: "Test Case Generator",
    description: "Comprehensive test suites with edge cases, mocks, and coverage targets",
    projectName: "Test Suite Architect",
    domain: "Software testing",
    projectDesc: "An AI assistant that generates test suites with happy path, edge case, error handling, and integration scenarios. Includes mock strategies, fixture design, and coverage gap analysis.",
    goals: "Produce test suites that catch regressions before production, cover non-obvious edge cases, and serve as living documentation of expected system behavior",
  },

  // ─── PREMIUM: Education (3) ───────────────────────────────────────────────
  {
    id: "course-outline",
    category: "education",
    tier: "pro",
    name: "Course Outline Builder",
    description: "Structured course curricula with learning objectives and assessments",
    projectName: "Course Curriculum Designer",
    domain: "Online education",
    projectDesc: "An AI assistant that designs course outlines with clear learning objectives per module, prerequisite mapping, progressive skill building, practical exercises, and assessment rubrics.",
    goals: "Build course structures that move students from beginner to competent through deliberate sequencing, with checkpoints that prevent knowledge gaps from compounding",
  },
  {
    id: "workshop-facilitator",
    category: "education",
    tier: "pro",
    name: "Workshop Facilitator Guide",
    description: "Run-of-show guides for live workshops with timing, activities, and transitions",
    projectName: "Workshop Facilitator",
    domain: "Professional training",
    projectDesc: "An AI assistant that creates detailed workshop facilitator guides with minute-by-minute run-of-show, group activity instructions, discussion prompts, energy management tactics, and contingency plans.",
    goals: "Produce facilitation guides that allow any prepared facilitator to deliver a high-energy, high-retention workshop without improvising or losing the room",
  },
  {
    id: "knowledge-base",
    category: "education",
    tier: "pro",
    name: "Internal Knowledge Base",
    description: "Company knowledge bases with searchable structure and maintenance workflows",
    projectName: "Knowledge Base Architect",
    domain: "Internal documentation",
    projectDesc: "An AI assistant that structures internal knowledge base articles with consistent formatting, progressive detail levels, cross-referencing, and ownership tagging for maintenance accountability.",
    goals: "Create knowledge bases that new hires actually use instead of asking Slack, that stay current through clear ownership, and that reduce repeated questions by 80%",
  },

  // ─── PREMIUM: Operations (3) ──────────────────────────────────────────────
  {
    id: "sop-writer",
    category: "operations",
    tier: "pro",
    name: "Standard Operating Procedure",
    description: "Step-by-step SOPs with decision trees and exception handling",
    projectName: "SOP Writer",
    domain: "Operations management",
    projectDesc: "An AI assistant that creates standard operating procedures with numbered steps, decision branch points, exception handling protocols, quality checkpoints, and role-specific instructions.",
    goals: "Write SOPs that any trained team member can follow to produce consistent results, with clear escalation paths for edge cases and measurable quality standards",
  },
  {
    id: "vendor-evaluation",
    category: "operations",
    tier: "pro",
    name: "Vendor Evaluation Framework",
    description: "Structured vendor comparisons with weighted scoring and risk assessment",
    projectName: "Vendor Evaluation Analyst",
    domain: "Procurement",
    projectDesc: "An AI assistant that builds vendor evaluation frameworks with weighted criteria, scoring rubrics, reference check scripts, TCO analysis templates, and risk-adjusted comparison matrices.",
    goals: "Make vendor selection decisions defensible and systematic rather than gut-driven, with clear documentation that satisfies procurement compliance requirements",
  },
  {
    id: "crisis-comms",
    category: "operations",
    tier: "pro",
    name: "Crisis Communication Plan",
    description: "Pre-written crisis response templates with escalation protocols",
    projectName: "Crisis Communications Writer",
    domain: "Corporate communications",
    projectDesc: "An AI assistant that prepares crisis communication plans with scenario-specific response templates, stakeholder notification sequences, media holding statements, and internal briefing scripts.",
    goals: "Have response plans ready before crises hit so the team can act within minutes rather than hours, with pre-approved language that protects reputation while being transparent",
  },
];
